version: "3"

services:
  geth:
    image: "ghcr.io/foundry-rs/foundry:latest"
    ports:
      - "8545:8545"
    command:
      - anvil
      - -p
      - '8545'
      - --host
      - '0.0.0.0'
      - --hardfork
      - 'london'
      - --prune-history
